Speech.create(title: "Automation in real life", description: "Some text", place: "Lviv", user_id: "4", conference_id: "1", theme_id: "2", date: DateTime.now + 1.day)
Speech.create(title: "Automation in real life", description: "Some text", place: "Kyiv", user_id: "4", conference_id: "1", theme_id: "1", date: DateTime.now + 1.day)
Speech.create(title: "Automation in real life", description: "Some text", place: "Kyiv", user_id: "5", conference_id: "2", theme_id: "1", date: DateTime.now + 2.day)
Speech.create(title: "Automation in real life", description: "Some text", place: "Kyiv", user_id: "5", conference_id: "2", theme_id: "2", date: DateTime.now + 2.day)
Speech.create(title: "Food additives and unhealthiness.", description: "About food", place: "Львів", user_id: "6", conference_id: "3", theme_id: "7", date: DateTime.now + 2.day)
Speech.create(title: "Food additives and unhealthiness.", description: "About food", place: "Львів", user_id: "6", conference_id: "3", theme_id: "7", date: DateTime.now + 2.day)
Speech.create(title: "Food additives and unhealthiness.", description: "About food", place: "Львів", user_id: "6", conference_id: "3", theme_id: "7", date: DateTime.now + 2.day)
Speech.create(title: "Food additives and unhealthiness.", description: "About food", place: "Львів", user_id: "6", conference_id: "3", theme_id: "7", date: DateTime.now + 2.day)